/*Mock up data to insert into the author, recipe, and ingredients table*/

INSERT INTO Authors(name) VALUES
('John Doe'), 
('Jane Doe'), 
('Julia Child'),
('Gordon Ramsay'),
('Nigella Lawson'),
('Jamie Oliver'),
('Paula Bean'),
('Bobby Flail'),
('Mary Fairy'),
('Chuck Dough');

INSERT INTO Recipes(title, instructions, author_id) VALUES
('Pizza', 'Bake in the oven for 15 minutes.', 1),
('Pasta', 'Boil for 10 minutes.', 2),
('Boeuf Bourguignon', 'First prepare the meat and vegetables. Then cook it slowly.', 3),
('Beef Wellington', 'First prepare the meat, then wrap it in a pastry and bake.', 4),
('Old Fashioned Chocolate Cake', 'Mix the ingredients and bake in the oven.', 5),
('The Perfect Roast Chicken', 'Prepare the chicken and roast in the oven.', 6),
('Unicorn Tacos', 'Open can of unicorn meat. Heat in pan. Serve in taco shells.', 7),
('Yeti Spaghetti', 'Boil water. Cook spaghetti. Hope you have a pet yeti.', 8),
('Invisible Pie', 'Mix ingredients. Bake in oven. Pretend to eat.', 9),
('Square Eggs', 'Try to figure out how to make an egg square. Give up. Make scrambled eggs instead.', 10);

INSERT INTO Ingredients(name, quantity, recipe_id) VALUES
('Flour', '2 cups', 1),
('Cheese', '1 cup', 1),
('Tomato Sauce', '1 cup', 1),
('Tomato Sauce', '1 cup', 2),
('Pasta', '200 grams', 2),
('Salt', '1 teaspoon', 2),
('Beef', '2 lbs', 3),
('Carrots', '3', 3),
('Onions', '2', 3),
('Red Wine', '1 bottle', 3),
('Beef Fillet', '1', 4),
('Mushrooms', '2 cups', 4),
('Pastry Dough', '1 sheet', 4),
('Egg Yolk', '1', 4),
('Flour', '2 cups', 5),
('Sugar', '1 cup', 5),
('Cocoa', '1/2 cup', 5),
('Eggs', '2', 5),
('Chicken', '1', 6),
('Salt', '1 tsp', 6),
('Pepper', '1/2 tsp', 6),
('Olive Oil', '2 tbsp', 6),
('Unicorn Meat', '1 can', 7),
('Rainbow Sauce', '1 bottle', 7),
('Taco Shells', '8', 7),
('Spaghetti', '200 grams', 8),
('Yeti Hair', '1 strand', 8),
('Tomato Sauce', '1 cup', 8),
('Imagination', '1 cup', 9),
('Belief in the Impossible', '1 cup', 9),
('Eggs', '2', 10),
('Frustration', '1 cup', 10),
('Optimism', '1 dash', 10);